### ISSUE TITLE
PFUser Support?

### ISSUE THREAD

**Issue by Alydyn** [sbonami/PFIncrementalStore#31]
Hello,
Does this support syncing the Parse User class?  If so is there anything special needed to map to a CoreData entity "User"?  Also, how do you handle not being able to write to User objects that are not logged in w/o the Master key?

Thanks for putting this together!
-Aaron

**Comment by sbonami** [comment]
Thanks for using PFIncrementalStore!

Right now the IncrementalStore syncs CoreData objects with PFObjects. Since the PFUser object is special and can't be selected with `[PFQuery queryWithClassName:@"User"]`, the IncrementalStore can't find it to sync with by merely assuming a `User` is equal to `PFUser`.

I did find that `[PFQuery queryWithClassName:@"_User"]` returns `PFUser` objects, however this doesn't look to be documented and could change at any time. And you also bring up a valid point about updating a user object without having proper credentials. I'll think through this a bit more and get back to you.

**Comment by davidhlee** [comment]
+1 I would love to see PFUser support!

**Comment by Alydyn** [comment]
I've thought a lot about PFUsers too and the challenges presented by Parse's implementation.  When I previously played around with using an NSIncrementalStore subclass I used AFIncrementalStore as a starting point and went from there.  In that implementation you subclass AFRestClient and can modify the URL's a bit.  For example I was able to use the Master key when a User object was detected (had to modify the URL as well since it is /users and not /classes/user).

Using the Master Key is not really a preferred option but for my purposes it was fine.  Another potentially viable option would be to create a new entity, "UserAttributes", with a one-to-one relationship to User objects.  Could either use Cloud Code or local code to establish and store all application generated info about the user there instead of the _User object.  It's a bit more of a pain but it may get around the issues inherent with the class.

**Comment by sbonami** [comment]
@Alydyn, thanks for the input and suggestion. I like the `UserAttributes` entity idea, I'm toying with that as well as an `NSManagedObject` category or something like it (most likely utilizing `PFSubclassing`). I'll try to post some code by the end of the weekend that wraps `PFUser`, and maybe `PFProduct`, `PFRole`, and `PFInstallation` as well.

**Comment by Alydyn** [comment]
@sbonami sounds good, thanks for the update!

**Comment by sbonami** [comment]
Almost there with a working solution! Although it's a WIP so I wouldn't go throwing it in a production app tomorrow ;)

**Comment by Alydyn** [comment]
@sbonami great! I have a data set that I can test it with. :)

**Comment by sbonami** [comment]
I've created pull request #33 with my initial thoughts on how to do this. Let me know what you think on that pull request.

**Comment by sbonami** [comment]
Hey @Alydyn and @davidhlee, just checkin in to see if either of you have had a chance to take a look at the code on pull request #33.

**Comment by Alydyn** [comment]
Hey @sbonami very sorry I have a deadline I have been frantically working against. :/
I'm working all day today on it and should have it released tomorrow, and then I plan on diving into PFIncrementalStore again.

Thank you!

**Comment by davidhlee** [comment]
Hi @sbonami--I've also been swamped lately. I'll try to give the PFUser support a test drive this weekend. Thanks so much for being so responsive, though--this is going to be a very helpful library!

**Comment by sbonami** [comment]
No worries gents, I appreciate the support and suggestions! I just wanted to make sure you were aware this was ready for some testing.

**Comment by yzoldan** [comment]
Hi, did you have any luck in testing your PFUser implementation?
Thanks!

**Comment by sbonami** [comment]
In short: yes! PFIncrementalStore started as a pod to be used in a few projects. Now that I have time to work on those projects, better testing of PFIS can commence! I'm going to be jumping back on development of this project, and that feature, soon!
