### ISSUE TITLE
Build upon AFIncrementalStore

### ISSUE THREAD

**Issue by hokster7** [sbonami/PFIncrementalStore#37]
https://github.com/AFNetworking/AFIncrementalStore

Again — uses Parse's REST API as well. I think by leveraging existing open-source project, we can structure Parse-specific code around that in consequence, limit the complexity of this project, making it more robust.

**Comment by Alydyn** [comment]
To the best of my knowledge, AFIncrementalStore has nothing to do with Parse.  Also, AFIS is designed to work with a more "traditional" REST API, and Parse's REST API has some unique differences that make it challenging without a custom implementation like @sbonami has put together.

**Comment by sbonami** [comment]
@Alydyn is correct, `PFIncrementalStore` is similar to `AFIncrementalStore` in that it utilizes Apple's `NSIncrementalStore`, but by using Parse's API we can leverage features and things that are potentially more cumbersome by mapping to REST endpoints. I figure that Parse has done the hard-work for us, why not use that?

**Comment by hokster7** [comment]
Fair enough! Was wondering.

I'd love to see some working example projects for with MagicalRecord though now. I haven't managed to PFIncrementalStore storing anything at all.

Thanks for this project btw: it could be helpful in decoupling the app implementation from Parse completely.
