### ISSUE TITLE
Co-maintainer needed!

### ISSUE THREAD

**Issue by sbonami** [sbonami/PFIncrementalStore#55]
PFIS forks, followers, and users:

I'm looking for a co-maintainer to keep PFIS alive. I've joined a company as lead dev and can't devote as much time as I'd like to maintain the repo. If you're interested in keeping the repo going, please reach out and discuss.

Thanks!

**Comment by callzhang** [comment]
Scott,

I have worked on PFIS with quite a few changes proposed. And I developed a
sync framework between PFObect and ManagedObect for a project in my
company. I would be happy to take over and continue the work.

Lei

**Comment by sbonami** [comment]
Thanks for stepping up! Commit-bit granted, looking forward to improvements to the repo!

**Comment by callzhang** [comment]
Thanks! It would be great if we could have a discussion about the architecture and thoughts behind your code sometime.

**Comment by sbonami** [comment]
Absolutely! My email is **redacted**, feel free to send me a message with your contact info and we can make something work!

**Comment by callzhang** [comment]
Cool! I will contact you at the end of the month, when my project is due.
